index:
  path: /
  controller: App\Controller\DefaultController::index
login:
    path: '/login'
    controller: 'App\Controller\LoginController::indexlogin'
  
user:
    path: '/user'
    controller: 'App\Controller\LoginController::indexUser'
admin:
    path: '/admin'
    controller: 'App\Controller\LoginController::indexadmin'

admin_users:
    path: /admin/users
    controller: 'App\Controller\AdminController::users'
admin_cours:
    path: /admin/cours
    controller: 'App\Controller\AdminController::cours'
    methods: ['GET']


admin_coursadd:
    path: /admin/cours/add
    controller: 'App\Controller\AdminController::newcours'
    methods: [POST,GET]

admin_coursupdate:
    path: /admin/cours/update
    controller: 'App\Controller\AdminController::updatecours'
    methods: [POST,GET]
cours_detail:
    path: /admin/cours/update/{id}
    controller: App\Controller\AdminController::coursDetail
    methods: [POST,GET]
cours_delete:
    path: /admin/cours/delete/{id}
    controller: App\Controller\AdminController::deleteCours
    methods: [POST,GET,DELETE]
admin_ebook:
    path: /admin/ebook
    controller: App\Controller\AdminController::ebook
admin_event:
    path: /admin/event
    controller: App\Controller\AdminController::event
admin_test:
    path: /admin/test
    controller: App\Controller\AdminController::test
admin_quiz:
    path: /admin/quiz
    controller: App\Controller\AdminController::quiz
user_profile:
    path: /user/profile
    controller: App\Controller\userController::index
user_cours:
    path: /user/cours
    controller: App\Controller\userController::cours
    methods: ['GET']
detaile_cours:
    path: /cours/{id}
    controller: 'App\Controller\userController::detaileCours'
    methods: ['GET']
    requirements:
        id: '\d+'
ajouter_commentaire:
    path: /cours/{id}/commentaire/ajouter
    controller: 'App\Controller\userController::ajouterCommentaire'
    methods: ['POST']
    requirements:
        id: '\d+'

user_ebooks:
    path: /user/ebooks
    controller: App\Controller\ebooksController::index
user_event:
    path: /user/event
    controller: App\Controller\eventController::index
user_test:
    path: /user/test
    controller: App\Controller\testController::index
user_quiz:
    path: /user/quiz
    controller: App\Controller\quizController::index