index:
  path: /
  controller: App\Controller\DefaultController::index
login:
    path: '/login'
    controller: 'App\Controller\LoginController::indexlogin'
  
user:
    path: '/user'
    controller: 'App\Controller\LoginController::indexUser'
admin:
    path: '/admin'
    controller: 'App\Controller\LoginController::indexadmin'

admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::users
admin_cours:
    path: /admin/cours
    controller: App\Controller\AdminController::newQuestion

admin_ebook:
    path: /admin/ebook
    controller: App\Controller\AdminController::ebook
admin_event:
    path: /admin/event
    controller: App\Controller\AdminController::event
admin_testadd:
    path: /admin/test/add
    controller: App\Controller\AdminController::newtest
    methods: [POST,GET]
admin_test:
    path: /admin/test
    controller: App\Controller\AdminController::test
admin_testupdate:
    path: /admin/test/update
    controller: App\Controller\AdminController::updatetest
    methods: [POST,GET]
admin_eventupdate:
    path: /admin/event/update
    controller: App\Controller\AdminController::updateevent
    methods: [POST,GET]
admin_eventadd:
    path: /admin/event/add
    controller: App\Controller\AdminController::newEvent
    methods: [POST,GET]
test_detail:
    path: /admin/test/update/{id}
    controller: App\Controller\AdminController::testDetail
    methods: [POST,GET]
event_detail:
    path: /admin/event/update/{EVENT_ID}
    controller: App\Controller\AdminController::eventDetail
    methods: [POST,GET]
test_delete:
    path: /admin/test/delete/{id}
    controller: App\Controller\AdminController::deleteTest
    methods: [POST,GET,DELETE]
event_delete:
    path: /event/delete/{EVENT_ID}
    controller: App\Controller\AdminController::deleteevent
    methods: [POST,GET,DELETE]
admin_quiz:
    path: /admin/quiz
    controller: App\Controller\AdminController::quiz
user_profile:
    path: /user/profile
    controller: App\Controller\userController::index
user_cours:
    path: /user/cours
    controller: App\Controller\coursController::index
user_ebooks:
    path: /user/ebooks
    controller: App\Controller\ebooksController::index
user_event:
    path: /user/event
    controller: App\Controller\eventController::index
user_test:
    path: /user/test
    controller: App\Controller\testController::index
user_quiz:
    path: /user/quiz
    controller: App\Controller\quizController::index
