index:
  path: /
  controller: App\Controller\CustomSecurityController::loginn
login:
    path: '/login'
    controller: 'App\Controller\LoginController::indexlogin'
  
user:
    path: '/user'
    controller: 'App\Controller\LoginController::indexUser'
admin:
    path: '/admin'
    controller: 'App\Controller\LoginController::indexadmin'

admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::users
admin_cours:
    path: /admin/cours
    controller: App\Controller\AdminController::cours

admin_ebook:
    path: /admin/ebook
    controller: App\Controller\AdminController::ebook
admin_event:
    path: /admin/event
    controller: App\Controller\AdminController::event
admin_test:
    path: /admin/test
    controller: App\Controller\AdminController::newtest
    methods: [POST,GET]
admin_quiz:
    path: /admin/quiz
    controller: App\Controller\AdminController::quiz
user_profile:
    path: /user/profile
    controller: App\Controller\userController::index
user_cours:
    path: /user/cours
    controller: App\Controller\coursController::index
user_ebooks:
    path: /user/ebooks
    controller: App\Controller\ebooksController::index
user_event:
    path: /user/event
    controller: App\Controller\eventController::index
user_test:
    path: /user/test
    controller: App\Controller\testController::index
user_quiz:
    path: /user/quiz
    controller: App\Controller\quizController::index

app_user_view:
    path: /user/view
    controller: App\Controller\userController::view
app_user_delete:
    path: /user/delete/{id}
    controller: App\Controller\userController::delete
app_user_count:
    path: /user/count
    controller: App\Controller\userController::nombreUtilisateurs
app_user_addd:
    path: /user/addd
    controller: App\Controller\userController::Add
app_user_edit:
    path: /user/edit/{id}
    controller: App\Controller\userController::edit
app_login:
    path: /login
    controller: App\Controller\CustomSecurityController::login
app_loginn:
    path: /loginn
    controller: App\Controller\CustomSecurityController::loginn
app_home:
    path: /home
    controller: App\Controller\CustomSecurityController::home
app_logout:
    path: /logout
    controller: App\Controller\CustomSecurityController::logout
app_user_profil:
    path: /user/editprofil/{id}
    controller: App\Controller\userController::editprofil
app_user_search:
    path: /user/search
    controller: App\Controller\userController::searchUser